### ISSUE TITLE
Time out on large files

### ISSUE THREAD

**Issue by stevevance** [openaddresses/pyesridump#16]
This parcel layer has 1.846 million features. 
````
esri2geojson http://gis2.cookcountyil.gov/arcgis/rest/services/cookVwrDynmcCondo/MapServer/44 condos.geojson
cli.esridump - INFO - Built 1846 requests using OID where clause method
Traceback (most recent call last):
  File "/usr/local/bin/esri2geojson", line 9, in <module>
    load_entry_point('esridump==1.1.1', 'console_scripts', 'esri2geojson')()
  File "/Library/Python/2.7/site-packages/esridump/cli.py", line 88, in main
    feature = feature_iter.next()
  File "/Library/Python/2.7/site-packages/esridump/dumper.py", line 360, in __iter__
    raise EsriDownloadError("Could not connect to URL", e)
esridump.errors.EsriDownloadError: ('Could not connect to URL', ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='gis2.cookcountyil.gov', port=80): Read timed out. (read timeout=30)",),))
````
It cuts out at 226 MB after 1 minute. I'm guessing the final version will be nearly 1 GB.

**Comment by iandees** [comment]
This is more of a problem that the server is getting overwhelmed than something wrong with the code. We could maybe add a retry and backoff timer so we don't hit the server quite as quickly as we do now.

**Comment by stevevance** [comment]
That would be great. 
I did figure out how to start where it left off after figuring out how many objects it was able to stuff into the output file, and then starting with that OBJECTID:

````
esri2geojson -f PIN14 -p "WHERE=OBJECTID > 1293400" --no-geometry http://gis2.cookcountyil.gov/arcgis/rest/services/cookVwrDynmcCondo/MapServer/44 condos_pins.geojson
````
But doing this again and again isn't a tenable solution if I'm trying to get all fields and the geometry.

**Comment by stevevance** [comment]
Here's another layer that times out:
https://services1.arcgis.com/kZsOWCED80XbRyJ0/ArcGIS/rest/services/MWRD_Layers/FeatureServer/1

````
cli.esridump - INFO - Built 1 requests using resultOffset method
esridump.errors.EsriDownloadError: ('Could not connect to URL', ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='services1.arcgis.com', port=443): Read timed out. (read timeout=30)",),))
````

**Comment by andrewharvey** [comment]
That's a good point raised by @stevevance , if you add a WHERE clause it can speed up the response and mean a timeout is less likely to happen. For some sources which have an `esriFieldTypeOID` field present where that's increment, if each successive call says where your OID > the last one you got, it can help a lot.

**Comment by andrewharvey** [comment]
@stevevance If the layer has an ID field, then I've found forcing esri2geojson to query by ID range avoids timeouts, you can now do this with `--paginate-oid`, from https://github.com/openaddresses/pyesridump/commit/a4c68db6025264e323bb73b9d901be6050ae6f7f. Could you try that and see if it makes a difference?
