### ISSUE TITLE
Outputs `NaN,NaN` for invalid geometry centroids

### ISSUE THREAD

**Issue by trescube** [openaddresses/pyesridump#31]
While working on [Orange County, NY](https://github.com/openaddresses/openaddresses/pull/2291), I tried dumping with pyesridump which worked but output invalid coordinates for geometries with a `NaN,NaN` centroid:

```
{
  "geometry": {
    "type": "Point",
    "coordinates": [
      NaN,
      NaN
    ]
  },
  "type": "Feature",
  "properties": {
    "OBJECTID": 147905,
    "CityStateZip": "MIDDLETOWN NY 10940",
    "UnitType": "",
    "StreetAddress": "88 DUNNING RD ",
    "UnitNumber": "",
    "SHAPE.fid": 146604
  }
}
```

I was unable to load the resulting geojson into QGIS.  It would be nice if pyesridump didn't output lines that have invalid coordinates.

**Comment by iandees** [comment]
This is tricky: I purposefully output `NaN` in the JSON because it's valid JSON, but the [GeoJSON spec is mildly ambiguous](https://tools.ietf.org/html/rfc7946#section-3.1.1):

> A position is an array of numbers.

...and in Javascript [`NaN` is a number](http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript).

I guess it boils down to what the expected behavior is. If a server responds with geometry that has `NaN` in it, do we ignore the geometry completely (and leave only the `properties`? Do we ignore the `NaN` coordinates and keep the rest of the geometry (in the case of a linestring or polygon)? Do we ignore the whole feature?

**Comment by trescube** [comment]
I tried to load the file as dumped by pyesridump (including the `NaN`'s) in the source but got:

```
2017-02-09 02:21:50,522  WARNING: Error doing conform; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ijson/backends/python.py", line 125, in parse_value
    yield ('number', common.number(symbol))
  File "/usr/local/lib/python3.4/dist-packages/ijson/common.py", line 158, in number
    number = decimal.Decimal(str_value)
  File "/usr/lib/python3.4/decimal.py", line 595, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "/usr/lib/python3.4/decimal.py", line 4050, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: 'N'
```

I only resort to pyesridump when the data URL times out a lot.  If they could be filtered out at the machine level for pyesridump exports, that would be great.  Otherwise, a script would have to be written and run to exclude the `NaN` records anyway.

**Comment by migurski** [comment]
Unfortunately, [`NaN` is not a valid number in JSON](http://json.org):

![JSON numbers](http://json.org/number.gif)

**Comment by iandees** [comment]
OK, so it's possible for Esri to output invalid JSON. We should make sure @slibby knows. But the question about what to do in this situation stands:

- skip the feature (and miss the non-geometry properties)
- skip the geometry (keep the feature but set geometry to null)

The second seems like the right thing to me, but I do remember running into a source that had a single NaN coordinate pair in a linestring once. Do we skip the coordinate pair or do we ditch the whole geometry?

**Comment by slibby** [comment]
Is there a specific feature from that layer that is returning NaN? I am seeing that feature that @trescube posted returning valid numbers, maybe they're outside the projection spatial extent or something?

http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0/query?geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&objectIds=147905&where=1%3D1&time=&returnCountOnly=false&returnIdsOnly=false&returnGeometry=true&maxAllowableOffset=&outSR=&outFields=*&f=pjson

**Comment by trescube** [comment]
Here are all 12 features in us/ny/orange that have `NaN,NaN` coordinates values:

```
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 2385, "CityStateZip": "NEWBURGH NY 12550", "UnitType": "", "StreetAddress": "258 N PLANK RD ", "UnitNumber": "", "SHAPE.fid": 2363}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 116937, "CityStateZip": "NEWBURGH NY 12550", "UnitType": "", "StreetAddress": "1 VIRGINIA CIR ", "UnitNumber": "", "SHAPE.fid": 115981}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 128929, "CityStateZip": "NEWBURGH NY 12550", "UnitType": "", "StreetAddress": "18 MASSACHUSETTS DR ", "UnitNumber": "", "SHAPE.fid": 127886}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 140703, "CityStateZip": "NEWBURGH NY 12550", "UnitType": "", "StreetAddress": "21 POMARICO DR ", "UnitNumber": "", "SHAPE.fid": 139618}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 147242, "CityStateZip": "NEWBURGH NY 12550", "UnitType": "", "StreetAddress": "99 ST RTE 17K ", "UnitNumber": "", "SHAPE.fid": 145943}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 147823, "CityStateZip": "MIDDLETOWN NY 10940", "UnitType": "", "StreetAddress": "88 DUNNING RD ", "UnitNumber": "", "SHAPE.fid": 146522}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 147905, "CityStateZip": "MIDDLETOWN NY 10940", "UnitType": "", "StreetAddress": "88 DUNNING RD ", "UnitNumber": "", "SHAPE.fid": 146604}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 149763, "CityStateZip": "WARWICK NY 10990", "UnitType": "", "StreetAddress": "6 DREW RD ", "UnitNumber": "", "SHAPE.fid": 148439}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 155387, "CityStateZip": "MONROE NY 10950", "UnitType": "", "StreetAddress": "5 LIPA FRIEDMAN LN ", "UnitNumber": "", "SHAPE.fid": 153988}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 155486, "CityStateZip": "MONTGOMERY NY 12549", "UnitType": "Apt", "StreetAddress": "979 ST RTE 17K Apt B", "UnitNumber": "B", "SHAPE.fid": 154083}},
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 155035, "CityStateZip": "WALLKILL NY 12589", "UnitType": "", "StreetAddress": "9 GOULD PL ", "UnitNumber": "", "SHAPE.fid": 153644}}
```

**Comment by slibby** [comment]
Seems to me these all return valid geoms from the ArcGIS Server (from the three I checked), leading me to believe it's something in the processing in pyesridump instead? 💵 = passed!

**Comment by thatdatabaseguy** [comment]
This issue also came up in the [Bogotá](https://github.com/openaddresses/openaddresses/pull/2542) and [Medellín](https://github.com/openaddresses/openaddresses/pull/2552) data sets in Colombia where again skipping the NaN entries and using a cached file worked, but would be preferable to handle it upstream.

In the case of Orange County, the ID field appears to be SHAPE.fid (which confusingly is typed as esriFieldTypeOID in the metadata despite the presence of an OBJECTID field which is just an integer). Querying with that field, it looks like the server does indeed return NaN:
- http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0/2363
- http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0/115981
- http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0/127886
