### ISSUE TITLE
Error when downloading layer 'Could not retrieve this chunk of objects: Failed to execute query. '

### ISSUE THREAD

**Issue by samtux** [openaddresses/pyesridump#42]
I have tried to download the layer of the following web link but always get an error that I could not identify:

http://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68

```
[samtux@ultrabook tmp]$ esri2geojson h
[samtux@ultrabook tmp]$ esri2geojson http://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68 prueba.geojson
2017-11-20 13:02:13,012 - cli.esridump - INFO - Built 1 requests using resultOffset method
Traceback (most recent call last):
  File "/usr/bin/esri2geojson", line 11, in <module>
    load_entry_point('esridump==1.7.0', 'console_scripts', 'esri2geojson')()
  File "/usr/lib/python2.7/site-packages/esridump/cli.py", line 103, in main
    feature = next(feature_iter)
  File "/usr/lib/python2.7/site-packages/esridump/dumper.py", line 394, in __iter__
    raise EsriDownloadError("Could not connect to URL", e)
esridump.errors.EsriDownloadError: ('Could not connect to URL', EsriDownloadError('Could not retrieve this chunk of objects: Failed to execute query. ',))
[samtux@ultrabook tmp]$ttp://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68 prueba.geojson
2017-11-20 13:02:13,012 - cli.esridump - INFO - Built 1 requests using resultOffset method
Traceback (most recent call last):
  File "/usr/bin/esri2geojson", line 11, in <module>
    load_entry_point('esridump==1.7.0', 'console_scripts', 'esri2geojson')()
  File "/usr/lib/python2.7/site-packages/esridump/cli.py", line 103, in main
    feature = next(feature_iter)
  File "/usr/lib/python2.7/site-packages/esridump/dumper.py", line 394, in __iter__
    raise EsriDownloadError("Could not connect to URL", e)
esridump.errors.EsriDownloadError: ('Could not connect to URL', EsriDownloadError('Could not retrieve this chunk of objects: Failed to execute query. ',))
[samtux@ultrabook tmp]$
```

**Comment by iandees** [comment]
In your example there it looks like the URL is split between two executions of the esri2geojson command. Can you try again and make sure the URL is passed in properly?

**Comment by samtux** [comment]
Sure @iandees , I've dealt with this layer and apparently it doesn't work with the esri2geojson command.

`> esri2geojson http://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68 test.geojson`

However, I have found that I can actually download the layer in GeoJSON format directly with the Query request in ArcGIS Server:

[http://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68/query?where=OBJECTID>0&outfields=*&f=geojson](
http://www.secretariadeambiente.gov.co/arcgis/rest/services/MapasVisorGeo/Cal_Aire_Geo/MapServer/68/query?where=OBJECTID>0&outfields=*&f=geojson)

Other layers of the same server if you can access and download with esri2geojson. I appreciate please if you can replicate the case with the esri2geojson command.
