### ISSUE TITLE
Large dataset timeout

### ISSUE THREAD

**Issue by jacksonvoelkel** [openaddresses/pyesridump#53]
When downloading a very large dataset, esri2geojson encounters this issue:

`./esri2geojson https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer/2 asdf.geojson
2018-05-22 12:52:15,082 - cli.esridump - INFO - Built 615 requests using OID where clause method
Traceback (most recent call last):
  File "./esri2geojson", line 11, in <module>
    sys.exit(main())
  File "/home/<username>/esridump/local/lib/python2.7/site-packages/esridump/cli.py", line 111, in main
    feature = next(feature_iter)
  File "/home/<username>/esridump/local/lib/python2.7/site-packages/esridump/dumper.py", line 425, in __iter__
    raise EsriDownloadError("Could not connect to URL", e)
esridump.errors.EsriDownloadError: ('Could not connect to URL', EsriDownloadError('https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer/2/query: Could not retrieve this chunk of objects HTTP 500 <html><head><title>Apache Tomcat/7.0.57 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException\n</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.57 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.57</h3></body></html>',))`

Multiple runs of the same command download a file between 10mb and 600mb, depending on when the connection is lost. I think it would be very beneficial for esri2geojson to not exit upon this error, but to continue down the queue of batches to download.

**Comment by sindile** [comment]
I am also experiencing this issue any suggestions on a work around.

**Comment by spaceof7** [comment]
I have had this problem with large datasets as well.  In my case I don't need the whole dataset so the workaround I used was to use some additional parameters to query a subset of the data.  You can query with a lat/lon bounding box(at least some servers) if you use:

esri2geojson -p geometryType=esriGeometryEnvelope -p geometry=-123.24,47.29,-122.50,48.01 -p spatialRel=esriSpatialRelIntersects -p inSR=4326 ...

If you need the whole dataset I suppose you could break it up into multiple subsets though i imagine you'd have to also clean up duplicate features.

**Comment by andrewharvey** [comment]
@jacksonvoelkel If the layer has an ID field, then I've found forcing esri2geojson to query by ID range avoids timeouts, you can now do this with `--paginate-oid`, from https://github.com/openaddresses/pyesridump/commit/a4c68db6025264e323bb73b9d901be6050ae6f7f. Could you try that and see if it makes a difference?

**Comment by bluetyson** [comment]
Thanks for the tips!
