### ISSUE TITLE
unable to download data from one specific ayer 

### ISSUE THREAD

**Issue by azimshaik** [openaddresses/pyesridump#69]
unable to download data from one layer (https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/4)
but works fine for 
(https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/0)
(https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/1)
(https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/2)
(https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/3)
Here is the error 
```
azimshaik91@cloudshell:~$ esri2geojson https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/4 test.geojson
2020-08-13 00:08:38,690 - cli.esridump - WARNING - Retrying https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/4 without SSL verification
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gis.ohiodnr.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2020-08-13 00:08:38,949 - cli.esridump - WARNING - Retrying https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/4/query without SSL verification
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gis.ohiodnr.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2020-08-13 00:09:01,274 - cli.esridump - INFO - Built 6262 requests using resultOffset method
2020-08-13 00:09:01,408 - cli.esridump - WARNING - Retrying https://gis.ohiodnr.gov/arcgis_site2/rest/services/OIT_Services/odnr_landbase_v2/MapServer/4/query without SSL verification
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gis.ohiodnr.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "/home/azimshaik91/.local/bin/esri2geojson", line 10, in <module>
    sys.exit(main())
  File "/home/azimshaik91/.local/lib/python2.7/site-packages/esridump/cli.py", line 114, in main
    feature = next(feature_iter)
  File "/home/azimshaik91/.local/lib/python2.7/site-packages/esridump/dumper.py", line 427, in __iter__
    raise EsriDownloadError("Could not connect to URL", e)
esridump.errors.EsriDownloadError: ('Could not connect to URL', ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='gis.ohiodnr.gov', port=443): Read timed out. (read timeout=30)",),))

```

More info:
(https://stackoverflow.com/questions/63388162/esri2geojson-could-not-connect-to-url-for-a-specific-layer-but-works-for-all-o)

**Comment by iandees** [comment]
Each layer can have a different database attached on the backend of the server. It looks like the one you're trying to query has a particularly slow database or the database isn't configured properly. There's not much you can do other than trying more than once to get it to download.
