### ISSUE TITLE
NoneType is not iterable, source does not support feature count

### ISSUE THREAD

**Issue by latot** [openaddresses/pyesridump#83]
Hi hi, here a weird map (?

```
esri2geojson https://geografia.ine.cl/server/rest/services/Agropecuario/Marco_Maestro_Agro/MapServer/0 test.geojson
2022-03-25 11:35:46,407 - cli.esridump - INFO - Source does not support feature count
Traceback (most recent call last):
  File "/home/user/Documentos/git/pyesridump/esridump/bin/esri2geojson", line 8, in <module>
    sys.exit(main())
  File "/home/user/Documentos/git/pyesridump/esridump/lib/python3.9/site-packages/esridump/cli.py", line 114, in main
    feature = next(feature_iter)
  File "/home/user/Documentos/git/pyesridump/esridump/lib/python3.9/site-packages/esridump/dumper.py", line 354, in __iter__
    oid_field_name = self._find_oid_field_name(metadata)
  File "/home/user/Documentos/git/pyesridump/esridump/lib/python3.9/site-packages/esridump/dumper.py", line 178, in _find_oid_field_name
    for f in metadata['fields']:
TypeError: 'NoneType' object is not iterable
```

Thx!

**Comment by iandees** [comment]
Looks like that's a "layer group" or something. You'll need to use layer 1 or 2, not 0.

**Comment by latot** [comment]
yes, is a layer group, a layer group will never have extra data that is not contained in the sublayers? because the server recognize the layer group as a layer.
